function scr_request_puzzle()
{
    var _url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";
    var _map = ds_map_create();
    
    /// Header (-H)
    ds_map_add(_map, "x-goog-api-key", GEMINI_API_KEY);
    ds_map_add(_map, "Content-Type", "application/json")
    
    /// -d
    var _prompt = "You are generating content for a game inspired by the NYT games Connections." +
                    "\n You need to create 4 categories each containing 4 different words/concepts." +
                    "\n The same words should never appear in more than 1 group." +
                    "\n Words/Concepts in this case can be single words, hyphyinated words and 2 word phrases like -shut up or come on" +
                    "\n Each category should get slightly more challenging than the one prior." +
                    "\n Categories can be made up of homophones, synonyms, trivia, words hidden within longer words ect" +
                    "\n Optionally increase difficulty by including red herrings ie words from different group that look like they can be in the same category" +
                    "\n Response should be formated as follows \n" + json_stringify(global.PUZZLE_TEMPLATE);
    var _data = {
                    contents: 
                    [ {
                        parts: 
                        [ {
                            text: _prompt, 
                        } ] 
                    } ]
                }
    
    //////////////////////////////// -X //// -H /////// -d ////////////
    request_id = http_request(_url, "POST", _map, json_stringify(_data));
    
    //ds_map_clear(_map);
    show_debug_message("data{0}", json_stringify(_data));
    //show_debug_message("requset {0}", request_id);
    
    /* Refernce from API -- REST --
     * 
    curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent" \
      -H "x-goog-api-key: $GEMINI_API_KEY" \
      -H 'Content-Type: application/json' \
      -X POST \  
      -d '{
        "contents": [
          {
            "parts": [
              {
                "text": "How does AI work?"
              }
            ]
          }
        ]
      }'
     * 
     */    
}

///@param {string} response the string generated by the AI
function clean_up_replace(_str)
{
    var _out =  string_replace_all(_str, "`", "");
    _out = string_replace(_str, "json", "");
    
    return _out;
    
}

function rewrite_reponse(_str)
{
    
}


///@param {string} response the string generated by the AI
function clean_up_response(_str)
{
    
    ///trim begining
    var _pos = 1;
    while (string_char_at(_str, _pos) != "[")
    {
        //if string_char_at(_str, _pos+1) != "]"
            _pos ++;
    }
    _str = string_delete(_str, 1, _pos-1)//string_trim_start(_str, _trim);
    
    //trim end
    _pos = string_length(_str);
    
    while (string_char_at(_str, _pos) != "]")
    {
        //if string_char_at(_str, _pos-1) != "]"
            _pos --;
    }
    _str = string_delete(_str, _pos+1, string_length(_str))
    
    return _str;
    
}