function scr_request_puzzle()
{
    var _url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";
    var _map = ds_map_create();
    
    /// Header (-H)
    ds_map_add(_map, "x-goog-api-key", GEMINI_API_KEY);
    ds_map_add(_map, "Content-Type", "application/json")
    
    /// -d
    var _prompt = "You are generating content for a game inspired by the NYT games Connections." +
                    "\n You need to create 4 categories each containing 4 different words." +
                    "\n The same word should never appear in more than 1 group." +
                    "\n Each category should get slightly more challenging than the one prior." +
                    "\n Response should be formated as follows" + json_stringify(global.PUZZLE_TEMPLATE);
    var _data = {
                    contents: 
                    [ {
                        parts: 
                        [ {
                            text: _prompt, 
                        } ] 
                    } ]
                }
    
    //////////////////////////////// -X //// -H /////// -d ////////////
    request_id = http_request(_url, "POST", _map, json_stringify(_data));
    
    //ds_map_clear(_map);
    show_debug_message("data{0}", json_stringify(_data));
    //show_debug_message("requset {0}", request_id);
    
    /* Refernce from API -- REST --
     * 
    curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent" \
      -H "x-goog-api-key: $GEMINI_API_KEY" \
      -H 'Content-Type: application/json' \
      -X POST \  
      -d '{
        "contents": [
          {
            "parts": [
              {
                "text": "How does AI work?"
              }
            ]
          }
        ]
      }'
     * 
     */    
}

///@param {string} response the string generated by the AI
function clean_up_response(_str)
{
    //var _out =  string_replace_all(_str, "'", "");
    // return _out;
    
    ///trim begining
    var _pos = 1;
    var _trim = ""
    while (string_char_at(_str, _pos) != "[")
    {
        _trim += string_char_at(_str, _pos);
        _pos ++;
    }
    _str = string_trim_start(_str, _trim);
    
    //trim end
    _pos = string_length(_str);
    _trim = "";
    
    while (string_char_at(_str, _pos) != "]")
    {
        _trim += string_char_at(_str, _pos);
        _pos --;
    }
    _str = string_trim_start(_str, _trim);
    
    return _str;
    
}