function scr_request_puzzle(_prompt)
{
    var _url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";
    var _map = ds_map_create();
    
    /// Header (-H)
    ds_map_add(_map, "x-goog-api-key", GEMINI_API_KEY);
    ds_map_add(_map, "Content-Type", "application/json")
    
    /// -d 
    var _data = {
                    contents: 
                    [ {
                        parts: 
                        [ {
                            text: _prompt, 
                        } ] 
                    } ],
                    // THIS PART ENABLES GROUNDING
                    tools: 
                    [ { "google_search": {} } ]
                }
    
    
    //////////////////////////////// -X //// -H /////// -d ////////////
    request_id = http_request(_url, "POST", _map, json_stringify(_data));
    
    //ds_map_clear(_map);
    show_debug_message("data{0}", json_stringify(_data));
    //show_debug_message("requset {0}", request_id);
    
    /* Refernce from API -- REST --
     * 
    curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent" \
      -H "x-goog-api-key: $GEMINI_API_KEY" \
      -H 'Content-Type: application/json' \
      -X POST \  
      -d '{
        "system_instruction": {
            "parts": [
              {"text": "You are a friendly pirate."}
            ]
        }
        "contents": [
          {
            "parts": [
              {
                "text": "How does AI work?"
              }
            ]
          }
        ]
      }'
     * 
     */    
}

///@param {string} response the string generated by the AI
function clean_up_replace(_str)
{
    var _out =  string_replace_all(_str, "`", "");
    _out = string_replace(_str, "json", "");
    
    return _out;
    
}




///@param {string} response the string generated by the AI
function clean_up_response(_str)
{
    
    ///trim begining
    var _pos = 1;
    while (string_char_at(_str, _pos) != "[")
    {
        _pos ++;
        
        //if search fails
        if (_pos == string_length(_str)) return noone;
        
    }
    _str = string_delete(_str, 1, _pos-1)//string_trim_start(_str, _trim);
    
    //trim end
    _pos = string_length(_str);
    
    while (string_char_at(_str, _pos) != "]")
    {
        _pos --;
    }
    _str = string_delete(_str, _pos+1, string_length(_str))
    
    return _str;
    
}